### ISSUE TITLE
.Xauthority

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#101]
.Xauthority can be tricky. It can be moved with XAUTHORITY envorment variable, except that there are couple of desktop environments that don't support this.

lightdm is oen, which is the default for Xubuntu. If XAUTHORITY is set, then the user won't be able to login.

A workaround this is to edit the file /etc/lightdm/lightdm.conf and add or edit the line
user-authority-in-system-dir=true
It seems that either this line is not there, or its set to false.

I found it in this page https://askubuntu.com/questions/960793/whats-the-right-place-to-set-the-xauthority-environment-variable

I then deleted $HOME/.Xauthority and rebooted, then it was in /var/run/lightdm/user/Xauthority

I think this variable would have to be set in .profile, so that it would be available during bootup, before .bashrc is processed

**Comment by magnus-ISU** [comment]
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

This works, it should be added as a rule.

**Comment by magnus-ISU** [comment]
In `/etc/security/pam_env.conf` you can put the line

    XAUTHORITY DEFAULT="${XDG_RUNTIME_DIR}/Xauthority"

I don't think there is a way to do this in userspace though.

**Comment by NoelJacob** [comment]
If I set it in profile I cannot login. It shows login screen again and again.

**Comment by sunhasgothishaton** [comment]
Yes, I think initially I intended it as an FYI. I forgot I left it open.
