### ISSUE TITLE
env.fish with more than two rules

### ISSUE THREAD

**Issue by gitfib** [doron-cohen/antidot#107]
I encountered two issues in fish:
1. Applying more than 2 rules with `EXPORT` would write the third rule over the second in `env.fish`
2. `antidot clean` asks me to run `eval "$(antidot init)"`, which in fish it would be `eval (antidot init)` - but running that gives error `fish: 'end' outside of a block`

SHELL=/usr/bin/fish
fish, version 3.1.2
antidot version 0.5.0

**Comment by doron-cohen** [comment]
Thanks for the report @gitfib . I do need to add some integration tests to catch these bugs. Looks like Fish normalizes newlines to spaces in `eval`. You should use `antidot init | source`. I will fix the documentation about that.

About the first issue I will investigate it and hopefully fix it today.

**Comment by doron-cohen** [comment]
@gitfib this is now fixed in 0.6.0. I just tested it on my machine (which also has fish) and released it. Please report if this issue is gone.

**Comment by gitfib** [comment]
I confirm it's fixed, except... I had to use `HOME=/tmp antidot clean`. Otherwise I got:
```
DEBUG: Key value store doesn't exist. Creating in /home/user/.local/share/antidot/kvstore.json
Failed to load key value store
Error: rename /tmp/atomic_****018802040 /home/user/.local/share/antidot/kvstore.json: invalid cross-device link
```
It seems to be related to [this line](https://github.com/doron-cohen/antidot/blame/fa90119a719f6825a5fd708d87c7a7301ff39fa5/internal/utils/files.go#L149), because [my /tmp is tmpfs and /home is btrfs](https://groups.google.com/g/golang-dev/c/5w7Jmg_iCJQ/m/hB_8mfV6pBUJ)

**Comment by doron-cohen** [comment]
Ok this is an easy fix I will do that today and publish a new release. I am closing this issue and will open a new one for that.

**Comment by doron-cohen** [comment]
@gitfib I just pushed https://github.com/doron-cohen/antidot/pull/114. If you are able to review or test it it will help me a lot. If not I will probably get to test this soon and publish a new version by tomorrow.
