### ISSUE TITLE
settings deleted

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#120]
I was running antidot 0.4.2 until yesterday, I upgraded to 0.6.2

On the next boot, some migrated files appeared again. It wasn't until today that I noticed that none of the migrated environment variables were set anymore.

I just checked $HOME/.local/share/env.sh and it was now empty.

Has anyone experienced this? Do I have to start again with this?

**Comment by sunhasgothishaton** [comment]
I think it would be good to make a backup of the settings files (env.sh, aliases.sh, etc) before they are updated, in case something goes wrong. Maybe that's what happened this this case? then the working copy can be restored.

**Comment by doron-cohen** [comment]
Right. I changed the way I manage envs and aliases. I should have thought about a migration path. Sorry about that. We need to think of a reasonable way to migrate since antidot will not read the current env file but completely overwrite it.

**Comment by doron-cohen** [comment]
@sunhasgothishaton I added a migration notice. I will think of an easy way to import existing configuration (maybe a `jq` command?).

**Comment by sunhasgothishaton** [comment]
Good to know what happened, migration will be very helpful.

**Comment by doron-cohen** [comment]
I am closing this for now. Lesson learned.
