### ISSUE TITLE
Add missing XDG_STATE_HOME

### ISSUE THREAD

**Issue by AlecsFerra** [doron-cohen/antidot#139]
see: https://wiki.archlinux.org/title/XDG_Base_Directory
    XDG_STATE_HOME
        Where user-specific state files should be written (analogous to /var/lib).
        Should default to $HOME/.local/state.

**Comment by doron-cohen** [comment]
Hi @AlecsFerra 
Thanks for the issue I see there's a new XDG var in town. Do you know the default paths in other OSes as well? I need to check if the library I am using has a definition for that.

**Comment by AlecsFerra** [comment]
Sadly I don't know I just discovered this variable reading the arch wiki

**Comment by doron-cohen** [comment]
I updated `xdg` go lib in #152 so we can now use it where it fits.
