### ISSUE TITLE
Add trivial rules from Arch wiki

### ISSUE THREAD

**Issue by doron-cohen** [doron-cohen/antidot#16]
We should add more rules to `rules.yaml`.

The main source right now is [this](https://wiki.archlinux.org/index.php/XDG_Base_Directory) Arch Linux wiki which is updated from time to time. There are 3 tables on that page: [supported](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Supported), [partial](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial) and [hardcoded](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Hardcoded). We want to first add the items from the partial table and maybe later look at hardcoded.

There is also some stuff in [this](https://www.reddit.com/r/linux/comments/971m0z/im_tired_of_folders_littering_my_home_directory/) Reddit post which may not be in the Arch wiki above.

**Comment by sunhasgothishaton** [comment]
There is also this page which has some entries that aren't on the arch page

https://wiki.debian.org/DotFilesList
