### ISSUE TITLE
Possible to remove dotfiles by using a fake $HOME?

### ISSUE THREAD

**Issue by Grafcube** [doron-cohen/antidot#199]
Would it be possible to automate something like what [this article](https://tomwh.uk/blog/posts/2020/03/28/fake-home-prison/) shows? It works by changing $HOME and launching applications from a script in `~/.local/bin`. With this it may be possible to clean up `.librewolf`, `.steam` and others like it.

**Comment by doron-cohen** [comment]
I tried this approach but it didnt work for some GUI applications which needed access for common apps config files (like ssh and aws creds). It may introduce other unknown issues as well

**Comment by doron-cohen** [comment]
I am going to close this issue since it isnt the approach of this tool
