### ISSUE TITLE
Make and AUR and I'll test the butter out of it :)

### ISSUE THREAD

**Issue by tiotrom** [doron-cohen/antidot#36]
I am using our own TROMjaro.com operating system and I got sick of these .files especially since I test hundreds of applications for our distribution. If you make an AUR for it so I can easily install and manage it (updates and all) I will test this a lot, since I am installing a ton of applications to test for our distro :).

Could be very useful for this little app to get some proper testing.
Thanks a lot for doing this!

**Comment by doron-cohen** [comment]
That is a good idea. I am currently looking for something that will distribute the releases to multiple distribution but I might start with AUR and Brew for starters. I will try to get to this this week.

**Comment by tiotrom** [comment]
Awesome. I'll test it a lot. ;)

**Comment by jedahan** [comment]
Btw I have it packaged for [kiss](k1ss.org) linux - you can view the package at https://github.com/jedahan/kiss-repo/tree/main/antidot .

**Comment by tiotrom** [comment]
Thanks. I am afraid I am not that knowledgeable to do this. Will see if I can do it. If you release this as AUR post an update please. Cheers!

**Comment by doron-cohen** [comment]
Someone already beat me to it: https://aur.archlinux.org/packages/antidot-bin/

**Comment by doron-cohen** [comment]
@tiotrom please let me know if the package works correctly when you are available for it. Thanks!

**Comment by tiotrom** [comment]
The AUR does not build I reported it to the AUR.

**Comment by doron-cohen** [comment]
@tiotrom thanks I fixed the URL and I will also push a fix to the CI

**Comment by tiotrom** [comment]
Hi. I apologize I was busy with other things. I looked more into this today and perhaps I misunderstood what it does. I thought that it automatically puts the .dot folders into something like .config folder and allows programs to use the folders from there. But I am not sure it does that. Plus, I thought users do not have to run it via a terminal to clean the system from such .dot folders.

So I was unable to properly understand how to use it. I need to look more into it.

**Comment by doron-cohen** [comment]
The main goal of this application is to clean your home directory from dotfiles. It will do so by moving them to the appropriate location (e.g. a config file to `$XDG_CONFIG_HOME`). But, in order for the application to still work correctly some environment variables or aliases should be declared (depending on the app). These are done by `antidot` while running the `clean` command. The only thing left to do is to add `eval "$(antidot init)` in your `.bashrc`.

**Comment by tiotrom** [comment]
Ok perhaps this is way too complicated for me so I apologize for saying that I will test it a lot. And perhaps no one from our tromjaro team, who would know how to test it, has time at the moment. Maybe if this was more "magical" in nature and one would install it and did all of the magic in the background, would be something I'd love to test and see if applications work with it. I will close this for now and I apologize again, I honestly thought this is a matter of installing antidot and then simply test many applications to see if all works correctly.

**Comment by doron-cohen** [comment]
I thought about this direction but came to the conclusion I wouldn't want to move these files without confirmation. Right now all you need to do is run `antidot clean` once and add `eval "$(antidot init)"` to `.bashrc`. Not that much of work.

I appreciate the intention. I hope you will find antidot useful in the future.

**Comment by tiotrom** [comment]
antidot clean - I did this. 

> add eval "$(antidot init)" to .bashrc

This I did not. Before I'll try to do that, what is this doing? Basically move all of the .files to .config? Including new ones from applications users will install on their system?

**Comment by doron-cohen** [comment]
When you run `antidot clean` you are moving files and creating aliases and exporting environment variables. In order to have these aliases and vars set in your shell you need to add `eval "$(antidot init)"` to your `.bashrc`. You can run `antidot init` and see the shell script that will run. It basically just ensures XDG variables are set and sources the aliases and vars files.
