### ISSUE TITLE
Fallback to common XDG values when not set with notification to user

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#37]
I  don;t have XDG_DATA_HOME (or any of the XDG directories) set and it gave the output below.

For cargo, it wanted to move it from /home/rob/.cargo to /cargo, shouldn't this be XDG_DATA_HOME/cargo or if XDG_DATA_HOME is not set, ~/.local/share. Does XDG_DATA_HOME fall back to ~/.local.share if its not set?
 
Rule cargo_home:
  MOVE   /home/rob/.cargo → /cargo
  EXPORT CARGO_HOME="${XDG_DATA_HOME}/cargo"
? Apply rule cargo_home? No

Rule less:
  MOVE   /home/rob/.lesshst → /less/history
  EXPORT LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
  EXPORT LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"
? Apply rule less? No

Rule cuda:
  MOVE   /home/rob/.nv → /nv
  EXPORT CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"
? Apply rule cuda? No

Rule nvidia-settings:
  MOVE   /home/rob/.nvidia-settings-rc → /nvidia/settings
  ALIAS nvidia-settings="nvidia-settings --config=${XDG_CONFIG_HOME}/nvidia/settings"
? Apply rule nvidia-settings? No

Rule parallel:
  MOVE   /home/rob/.parallel → /parallel
  EXPORT PARALLEL_HOME="${XDG_CONFIG_HOME}/parallel"
? Apply rule parallel? No

Rule rustup:
  MOVE   /home/rob/.rustup → /rustup
  EXPORT RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
? Apply rule rustup? No

**Comment by doron-cohen** [comment]
Yes you are right. I should add a default fallback for the XDG vars and notify the user. Thanks!

**Comment by doron-cohen** [comment]
A quick fix here will be to set these variables of course. `antidot init` will do that for you BTW.

**Comment by sunhasgothishaton** [comment]
Thanks, I'll add antidot init to my .profile

**Comment by fosspill** [comment]
If I'm not mistaken ${XDG_CONFIG_HOME} (and the alike) should only be set if you want to override the default. Hence you should not assume the availability of those variables.

**Comment by doron-cohen** [comment]
I would like the behavior of this utility to be as clear as possible. I think printing the fallback values to the user is important. I could have thought otherwise a year ago when I was working on Linux. But, on Mac OS the defaults are not a consensus at all.
