### ISSUE TITLE
nvidia GL shader cache dot directory

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#40]
I don't know where to add this, so I'll try it here.

Nvidia has a directory it uses for cache called GLCache , by default it is stored in ~/.nv

To move this directory the environment variable __GL_SHADER_DISK_CACHE_PATH can be set to $XDG_CACHE_HOME/nv for it to be with the other nvidia cache directories.

Is this where I can add dotfiles for moving?

Thanks,
Rob

**Comment by doron-cohen** [comment]
Thanks. I was looking for documentation on how to move this directory properly but I couldnt find it. I will add this to the rules file promptly.

**Comment by sunhasgothishaton** [comment]
I removed __GL_SHADER_DISK_CACHE_PATH from my .profile so I will let antidot manage it.

Now antidot wants to use it for for CUDA, I know that the rule for the shader isn't in the rules yet, its that there are two sub directories  in ~/.nv and they need to be managed separately. Currently, it seems that .nv is handled in one go. So maybe the CUDA needs to be changed too? so that it looks for ~/.nv/ComputerCache rather than just ~/.nv ?

This is what antidot found when I had GLCache in ~/.nv it had previously moved ~/.nv/ComputerCache for CUDA

Rule cuda:
  MOVE   /home/rob/.nv → /home/rob/.cache/nv
  EXPORT CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"
? Apply rule cuda? No

Thanks,
Rob

**Comment by doron-cohen** [comment]
The solution is to add another action. Just to make sure, `__GL_SHADER_DISK_CACHE_PATH` should be set to `$XDG_CACHE_HOME/nv`?

**Comment by sunhasgothishaton** [comment]
Ah right, got you, I understand what this more now.

Yes, __GL_SHADER_DISK_CACHE_PATH would be best set to $XDG_CACHE_HOME/nv
that is what I set it to on my computer.

What a great program you've made.

Thanks,
Rob

**Comment by doron-cohen** [comment]
I pushed a PR that solves this: https://github.com/doron-cohen/antidot/pull/41

**Comment by doron-cohen** [comment]
You can now `antidot update` and the new rule will take affect.

**Comment by sunhasgothishaton** [comment]
That's fantastic, excellent. Just tried it and it works great.

Thanks,
Rob
