### ISSUE TITLE
Allow overwriting XDG_ vars in antidot init

### ISSUE THREAD

**Issue by jedahan** [doron-cohen/antidot#42]
For example, with zsh:

```go
fmt.sprintf("export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-%s}", xdg.ConfigHome)
```

**Comment by doron-cohen** [comment]
Thanks for the suggestion. Will push a PR soon.

**Comment by jedahan** [comment]
Thank you! Note that I am not sure if that construct will work in all shells, not sure what you are targeting.

**Comment by doron-cohen** [comment]
I attend to support additional shells soon. I myself use fish shell so I have the motivation.
