### ISSUE TITLE
yarn support

### ISSUE THREAD

**Issue by jedahan** [doron-cohen/antidot#47]
just starting to make a tracking ticket so people can share research and ultimately make the correct rule

**Comment by doron-cohen** [comment]
Thanks @jedahan . Could you add to the tickets some information like the dotfile name and whether ifs a file or a directory. I should probably work on an issue template.

**Comment by jedahan** [comment]
According to https://github.com/yarnpkg/yarn/commit/2d454b552d447a0f79a04e4e451e926e1c0a29e7

I think its:
~/.yarn/link -> XDG_DATA_HOME/yarn/link
~/.yarn/global -> XDG_DATA_HOME/yarn/global
~/.yarn/config -> XDG_CONFIG_HOME/yarn/config
~/.yarnrc -> XDG_CONFIG_HOME/yarn/config

**Comment by doron-cohen** [comment]
@jedahan could you test the rules file from the PR I pushed?
