### ISSUE TITLE
qrcp support

### ISSUE THREAD

**Issue by jedahan** [doron-cohen/antidot#49]
XDG request here https://github.com/claudiodangelis/qrcp/issues/187
project here https://github.com/claudiodangelis/qrcp/

could currently be worked around by settings the alias `qrcp='qrcp --config ${XDG_CONFIG_HOME}/qrcp.json'` or something like that.

**Comment by claudiodangelis** [comment]
Hello, `qrcp` author here, the tool now supports XDG_CONFIG_HOME.

**Comment by doron-cohen** [comment]
Thanks @claudiodangelis . Does that mean it will auto detect the config in `XDG_CONFIG_HOME` ?

**Comment by claudiodangelis** [comment]
> Thanks @claudiodangelis . Does that mean it will auto detect the config in `XDG_CONFIG_HOME` ?

Yes, it will: https://github.com/claudiodangelis/qrcp/blob/master/config/config.go#L300

Props to @samhh who worked at this.

**Comment by jedahan** [comment]
@doron-cohen it will auto-detect, but still default to non-xdg style if both are found, which I think means we still want antidot to be able to migrate.

Also I wonder if antidot should detect if both exist and deviate. Generally most implementations I have seen choose XDG first and fallback to non-XDG, so this might be a special case.

**Comment by claudiodangelis** [comment]
@jedahan good point. I can't find an example, so please let me ask you: do CLI tools facing a config file path change usually manage the migration themselves? Whose responsibility of migrating/cleaning up config files when their paths change over time?

Thanks,
C

**Comment by jedahan** [comment]
Usually the tools do not do anything 'smart' like migration.
They simply have a list of places to look, and read from that list in order.
They usually do not inform the user where they are reading from by default either (sometimes share with a debug env variable).
