### ISSUE TITLE
Add a note or warning to a rule to be printed to the user

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#68]
Sometimes during a migration, a command has to be run e.g. to reset a system running

I just tried to manually migrate gnupg from ~/.gnupg to ~/.local/share/gnupg and for one of my tests, I had to run "gpgconf --kill gpg-agent" before I was able to create a private key. They key agent was still looking in the old directory.

Does antidot support the running of commands during migration?

**Comment by doron-cohen** [comment]
Not right now. I am parted about running commands. On one hand it will make this tool a lot powerful and I am sure there are other use cases as well. On the other hand, it will introduce security issues and will make this tool more like a script runner. I did think about adding the option to include a warning or a note that will be printed for a specific rule. That will make it easy to let the user know this command needs to be run after the migration.

**Comment by sunhasgothishaton** [comment]
I agree with you about it being a security issue, good call on that.

I like the idea to inform the user to run the commands after migration, it keeps the user in control too.

**Comment by jedahan** [comment]
Very much like the current simplicity of the application. Adding friendly directions for the user is nice though.
