### ISSUE TITLE
Remove check for init var value

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#70]
I did an antidot clean earlier and .gnupg got migrated

I ran gpg and then ~/.gnupg got created as env.sh hadn't been reloaded to set GNUPGHOME

I run source .profile (where I have $(antidot init) and nothing more was loaded, as ANTIDOT_INIT=1 was set, it wasn't loaded again.

In the end, I restarted my computer and it loaded the new variables and it was all working correctly. Is there a way I can load them without restarting my computer?

**Comment by doron-cohen** [comment]
This is a bug. The init variable needs to go. I wanted to save some cpu cycles but I guess that it should source the files after every change. I will just remove that check. Thanks
