### ISSUE TITLE
support bash history

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#71]
.bash_history can be moved by setting HISTFILE

I know its more of a system file than an application file, are these something you'd consider migrating too?

I suggest moving to $XDG_CACHE_HOME/bash/bash_history
or to
$XDG_CACHE_HOME/bash/history

see "help history" for details

**Comment by doron-cohen** [comment]
Yes I think these could be considered dotfiles too. Will add a rule. Thanks
