### ISSUE TITLE
trouble adding antodot to run in .bashrc

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#72]
I've been having trouble with adding $(~/bin/antidot init) in .bashrc

When I do, I get the error message
if : command not found
at the beginning of each terminal I open

So for now, I have copied and pasted the code that antidot init prints into my .bashrc file

Am I making an error or is this a bug?
I'm running bash 4.4.20 with xubuntu 18.04.5

**Comment by doron-cohen** [comment]
Hi, could you paste here the way you used `antidot init` in your `.bashrc`?

I suspect that while `.bashrc` is running something is not initialized. Could you put this in your `.bashrc`, restart the shell and paste here the file contents?

```
antidot init > /tmp/antidot-test
```

**Comment by sunhasgothishaton** [comment]
I  have tried by adding $($HOME/bin/antidot init) to my .bashrc
I have also tried `$HOME/bin/antidot init` and run it without quotes just to try it.

see below for the output of the tmp file  :

if [[ "$ANTIDOT_INIT" != "1" ]]; then
  export XDG_CONFIG_HOME="/home/rob/.config"
  export XDG_CACHE_HOME="/home/rob/.cache"
  export XDG_DATA_HOME="/home/rob/.local/share"

  source /home/rob/.local/share/antidot/env.sh
  source /home/rob/.local/share/antidot/alias.sh

  export ANTIDOT_INIT=1
fi

**Comment by doron-cohen** [comment]
That is very weird. But, since I attend to remove the `if` clause all together I think it is better to try again after the next release.

**Comment by sunhasgothishaton** [comment]
Yes, that's a good idea. I will wait to try this again after the next release.

**Comment by baryluk** [comment]
There is some issue with new line characters I think or something, because if I try to run $(./antidot init), all the output lines are concatenated into one line, and I got syntax error from bash

**Comment by baryluk** [comment]
@doron-cohen Could you add semicolons at the end of every line in the output of `antidot init`, I think it might help with some stuff. My bash is complaining a bit otherwise.

**Comment by sunhasgothishaton** [comment]
I'm stil getting a problem with shell integration

If I put in $(antidot init) I'm getting  the following each time I open a shell
bash: export: `/home/rob/.local/share/antidot/env.sh': not a valid identifier
bash: export: `/home/rob/.local/share/antidot/alias.sh': not a valid identifier

Its worse now, as XDG_CONFIG_HOME is being set as "${XDG_CONFIG_HOME:-/home/rob/.config}"; rather than /home/rob/.config
 and messing up new migrations. If I paste the output of antidot init into .bashrc then it works correctly.

This is what happens with antidot clean now
  NOTICE You may have to restart gpg-agent with 'gpgconf --kill gpg-agent'
  MOVE   /home/rob/.gnupg → "${XDG_DATA_HOME:-/home/rob/.local/share}";/gnupg
  EXPORT GNUPGHOME="${XDG_DATA_HOME}/gnupg"

I'm using antidot 0.4.1

I have tested this on xubuntu 18.04.5 and opensuse tumbleweed to check if I had a configuration problem, its the smae on both.

**Comment by doron-cohen** [comment]
Could you paste the output of `antidot init` and how you call it from `.bashrc`? Please put it inside triple backticks (```) so it will be formatted properly and easier to read.

**Comment by sunhasgothishaton** [comment]
This is the output from antidot init

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-/home/rob/.config}";
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-/home/rob/.cache}";
export XDG_DATA_HOME="${XDG_DATA_HOME:-/home/rob/.local/share}";

source /home/rob/.local/share/antidot/env.sh
source /home/rob/.local/share/antidot/alias.sh

***

I call it from .bashrc with $(antidot init)
I have also tried `antidot init`

I just tried `./antidot init` from the command line and it gave 
```bash: export: `/home/rob/.local/share/antidot/env.sh': not a valid identifier```
```bash: export: `/home/rob/.local/share/antidot/alias.sh': not a valid identifier```

it also set XDG_DATA_HOME incorrectly as before, I just tried `env | grep XDG` and the variables have been set to
```XDG_CACHE_HOME="${XDG_CACHE_HOME:-/home/rob/.cache}";```
```XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-/home/rob/.config}";```
```XDG_DATA_HOME="${XDG_DATA_HOME:-/home/rob/.local/share}";```

**Comment by baryluk** [comment]
@sunhasgothishaton try `eval $(antidot init)`.

I had same issue here https://github.com/doron-cohen/antidot/issues/73#issuecomment-744057422

>  env | grep XDG and the variables have been set to
```
XDG_CACHE_HOME="${XDG_CACHE_HOME:-/home/rob/.cache}";
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-/home/rob/.config}";
XDG_DATA_HOME="${XDG_DATA_HOME:-/home/rob/.local/share}";
```

This shows that they were NOT set.

it should show this instead:

```
XDG_CACHE_HOME="/home/rob/.cache";
XDG_CONFIG_HOME="/home/rob/.config";
XDG_DATA_HOME="/home/rob/.local/share";
```

This is why `eval` is needed, otherwise the variables get incorrectly assigned to literal string `${XDG_CACHE_HOME:-/home/rob/cache/}`. Then apps will literally create a directory named `${XDG_CACHE_HOME:-`  (yes!), with subdirectory `home`, with subcirectory `rob`, with subdirectory `cache`, with subdirectory `}`  (yes!).

**Comment by sunhasgothishaton** [comment]
I just put `evnal $(antidot init)` and now it works correctly.

Thank you so much, thats fixed it.

**Comment by doron-cohen** [comment]
Thanks @baryluk I don't know why I thought it would work otherwise...

**Comment by sunhasgothishaton** [comment]
I just noticed that now my aliases aren't being set now, the variables are being set though.

**Comment by doron-cohen** [comment]
You might need to wrap the antidot init output in double quotes. Like `eval "$(antidot init)"`. Please report if this works.

**Comment by sunhasgothishaton** [comment]
Yes, It works correctly. Fantastic.

**Comment by doron-cohen** [comment]
Great. I updated the README
