### ISSUE TITLE
I use antidot init in .profile and .bashrc

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#84]
This is more open for discussion and FYI  on my experience as peoples usage needs may vary, depending on computer setup.

I have found that I have to set antidot init in .profile and .bashrc

I have to put it in .profile as __GL_SHADER_DISK_CACHE_PATH has to be set int there after migration. If it isn't, then ~/.nv gets created again

I also set it in .bashrc as if I run antidot clean, then I only have to open a new terminal window to load the new variables and aliases. For .profile I would have to logout then login, or reboot to refresh new variables and aliases after migration

**Comment by doron-cohen** [comment]
Could you solve it by adding the antidot init script only in `.profile` and source `.profile` from `.bashrc`?

**Comment by sunhasgothishaton** [comment]
in Ubuntu, .profile calls .bashrc (only runs if interactive shell, so on bootup it wont process .bashrc). If I add `source .profile` in .bashrc it will be an infinite loop.

Adding to both .profile and .bashrc has been effective to me. Is there any downside to this?

**Comment by doron-cohen** [comment]
I can't think of one

**Comment by sunhasgothishaton** [comment]
Great, I'll use it this way for now.

**Comment by sunhasgothishaton** [comment]
Oh yes, I forgot what I initially added this one for. It for an FYI in case anyone else had this problem. Its a way for any software started via graphical menu to use the environmental variables.

It works ok, with (hopefully) no side effects.

**Comment by doron-cohen** [comment]
Happy to hear it works! Can this issue be closed then?
