### ISSUE TITLE
Add a message to source the env and alias files after antidot init

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#87]
I migrated gnupg (from $HOME/.gnupg to $XDG_CONFIG_HOME/gnupg) thIen  ran `gpg --list-keys` and it created $HOME/.gnupg as GNUPGHOME hadn't been set.

What was required at that point was for me to open a new terminal to refresh env.sh and then GNUPGHOME was set.

I think it would be good to either
1) warn the user to close and open the terminal after cleanup migration
or.
2) source `env.sh` and `aliases.sh` after cleanup to load the new variables for immediate use.

Thinking about it, I think the seconds one would be more user friendly as they don't have to do any more to load new variables after cleanup migration

**Comment by doron-cohen** [comment]
Well running `eval $(antidot init` (or restarting the shell if you have it in your `.bashrc` file) should be the recommended way. It is also true for all dotfiles. None of the rules requiring alias or a new env will work without it.
