### ISSUE TITLE
Source files on init only if they exist

### ISSUE THREAD

**Issue by sunhasgothishaton** [doron-cohen/antidot#88]
I have a test system so I wanted to  try antidot on that. Before I ran `antidot clean` I ran `antidot init` and added to contents to my .bashrc file

Upon opening a new terminal, it said
`bash: /home/rob/.local/share/antidot/alias.sh: No such file or directory`
`bash: /home/rob/.local/share/antidot/env.sh: No such file or directory`

Should these get created when `antidot init` is run (if they don't exist)?

After running `antidot clean` I opened a new terminal and got
bash: /home/rob/.local/share/antidot/alias.sh` as only environment variables were needed during this migration, seems that only env.sh was created

Should these get created when `antidot init` is run (if they don't exist)?

**Comment by doron-cohen** [comment]
Right. This is a bug. I should source them only if they exist.
